ppo:
  lr: 0.0005
  gamma: 0.99
  epsilon_clip: 0.1
  k_epochs: 3
  self_play_games: 100
  max_moves: 100
  device: "cpu"
  print_self_play: false
paths:
  save_model_path: "models/chess_ppo_checkpoint.pth"
  load_model_path: "models/chess_ppo_checkpoint.pth"
  games_dir: "self-play-games"
  games_per_file: 25
  metrics_dir: "training-metrics"
  metrics_format: "json"
evaluation:
  eval_games: 20
  plot_metrics: true
  metrics_smoothing: 10
agent:
  aggression: 0.0